myproject/core/urls.py
from django.urls import path
from myproject.core import views as v


app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),
    path('my_http_response/', v.my_http_response, name='my_http_response'),
    path('my_render_to_response/', v.my_render_to_response, name='my_render_to_response'),
    path('user/', v.users, name='users'),
    path('user/<int:pk>/', v.user_detail, name='user_detail'),
    path('ping/', v.ping, name='ping'),
    path('person/<int:pk>/', v.person_detail, name='person_detail'),
    path('person/redirected/<int:pk>/', v.person_redirected, name='person_redirected'),
    path('person/', v.persons, name='persons'),
    path('person/redirected/', v.persons_redirected, name='persons_redirected'),
    path('book/', v.BookListView.as_view(), name='book_list'),
    path('book/<int:pk>/', v.book_detail, name='book_detail'),
    path('book/add/', v.book_create, name='book_create'),
    path('book/add2/', v.BookCreateView.as_view(), name='book_create2'),
    path('book/redirected/', v.book_redirected, name='book_redirected'),
    path('ping/json/', v.ping_json, name='ping_json'),
]

myproject/urls.py
from django.urls import include, path
from django.contrib import admin
urlpatterns = [
    path('', include('myproject.core.urls', namespace='core')),
    path('admin/', admin.site.urls),
]

myproject/core/models.py
from django.db import models
from django.urls import reverse_lazy


class Person(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ('name',)
        verbose_name = 'pessoa'
        verbose_name_plural = 'pessoas'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('core:person_redirected', kwargs={'pk': self.pk})


class Book(models.Model):
    title = models.CharField('título', max_length=50, unique=True)

    class Meta:
        ordering = ('title',)
        verbose_name = 'livro'
        verbose_name_plural = 'livros'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('core:book_detail', kwargs={'pk': self.pk})

myproject/core/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = '__all__'

myproject/core/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.template.loader import render_to_string
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView
from .forms import BookForm
from .models import Person, Book


rendered = render_to_string('my_template.html', {'name': 'render_to_string'})


def my_http_response(request):
    return HttpResponse(rendered)


def my_render_to_response(request):
    return render_to_response('my_template.html', {'name': 'render_to_response'})


@login_required(login_url=reverse_lazy('admin:login'))
def users(request):
    return HttpResponse('<h1>Users</h1>')


def user_detail(request, pk):
    return HttpResponse(f'User {pk}')


def ping(request):
    print(request.GET)
    name = request.GET.get('name')
    return HttpResponse(f'pong {name}')


def index(request):
    template_name = 'index.html'
    return render(request, template_name)


def person_redirected(request, pk):
    person = Person.objects.get(pk=pk)
    return HttpResponse(f'<p>Você foi redirecionado! pk: {pk}</p><p>{ person.name }</p>')


def person_detail(request, pk):
    obj = Person.objects.get(pk=pk)
    print('Você será redirecionado')
    return redirect(obj)


def persons_redirected(request):
    return HttpResponse(f'<p>Você foi redirecionado!</p>')


def persons(request):
    print('Você será redirecionado')
    return redirect('core:persons_redirected')


def book_detail(request, pk):
    book = Book.objects.get(pk=pk)
    return HttpResponse(f'Book: {book}')


class BookListView(ListView):
    model = Book


def book_create(request):
    form = BookForm(request.POST or None)
    template_name = 'core/book_add.html'

    if request.method == 'POST':
        ...
        if form.is_valid():
            ...
            new_obj = form.save()
            # kw = {'pk': new_obj.pk}
            # return HttpResponseRedirect(reverse('core:person_detail', kwargs=kw))
            return redirect('core:book_detail', new_obj.pk)
        msg_error = form.errors.get('title')[0]
        messages.error(request, msg_error)
        return redirect('core:book_list')

    context = {'form': form}
    return render(request, template_name, context)


class BookCreateView(CreateView):
    model = Book
    fields = '__all__'
    # Se quiser ir direto para o objeto criado então use get_absolute_url.
    # O reverse vai dar erro.
    # success_url = reverse_lazy('core:book_list')

    def get_success_url(self):
        # Se não quiser usar o get_absolute_url e quiser passar
        # a instância criada para redirecionar manualmente...
        return reverse_lazy('core:book_detail', kwargs={'pk': self.object.pk})
        # ou
        # return reverse_lazy('core:book_detail', args=(self.object.pk,))


def book_redirected(request):
    return HttpResponseRedirect(reverse('core:book_list'))


# def ping_json(request):
#     name = request.GET.get('name')
#     age = request.GET.get('age')
#     data = {
#         'name': name,
#         'age': age
#     }
#     return JsonResponse(data)


def ping_json(request):
    name = request.GET.get('name')
    age = request.GET.get('age')
    data = {}
    if name:
        data['name'] = name
    if age:
        data['age'] = age
    return JsonResponse(data)

myproject/core/templates/core/book_add.html
<!-- book_add.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
  <title>Definitions</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

  <style>
    body {
      margin-top: 20px;
    }
  </style>
</head>
<body>
  <div class="container">
    <form action="." method="POST">
      {% csrf_token %}

      <label for="id_title">Título:</label>
      <input type="text" name="title" maxlength="60" required="" id="id_title">

      <button class="btn btn-primary" type="submit">Salvar</button>
    </form>
  </div>
</body>
</html>

myproject/core/templates/core/book_form.html
<!-- book_form.html -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
  <title>Definitions</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

  <style>
    body {
      margin-top: 20px;
    }
  </style>
</head>
<body>
  <div class="container">
    <form action="." method="POST">
      {% csrf_token %}
      {{ form }}
      <button class="btn btn-primary" type="submit">Salvar</button>
    </form>
  </div>
</body>
</html>

myproject/core/templates/core/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
  <title>Definitions</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

  <style>
    body {
      margin-top: 20px;
    }
  </style>
</head>
<body>
  <div class="container">
    {% for message in messages %}
      {% if 'success' in message.tags %}
      <p class="alert alert-success" role="alert"><span style="font-weight:bold">{{ message }}</span></p>
      {% else %}
      <p class="alert alert-danger" role="alert"><span style="font-weight:bold">{{ message }}</span></p>
      {% endif %}
    {% endfor %}

    <ul>
      {% for person in object_list %}
        <li>{{ person }}</li>
      {% endfor %}
    </ul>
  </div>

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

<script>
  //close alert after 3 seconds
  window.setTimeout(function() {
    $(".alert").fadeTo(500, 0).slideUp(500, function(){
      $(this).remove();
    });
  }, 3000);
</script>

</body>
</html>

myproject/core/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
  <title>Django Definições</title>
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>
  <div class="jumbotron">
    <h1>Django Definições</h1>
  </div>

  <ul>
    <li>
      <a href="{% url 'core:my_render_to_response' %}">render_to_response</a>
    </li>
    <li>
      <a href="{% url 'core:my_http_response' %}">http_response</a>
    </li>
    <li>
      <a href="{% url 'core:users' %}">users</a>
    </li>
    <li>
      <a href="{% url 'core:user_detail' 1 %}">user_detail</a>
    </li>
    <li>
      <a href="{ url 'core:person_redirected' 1 %}">person_redirected</a>
    </li>
    <li>
      <a href="{% url 'core:persons' %}">persons</a>
    </li>
    <li>
      <a href="{% url 'core:person_detail' 1 %}">person detail</a>
    </li>
    <li>
      <a href="{ url 'core:persons_redirected' %}">persons_redirected</a>
    </li>
    <li>
      <a href="{ url 'core:user_redirected' 1 %}">user_redirected</a>
    </li>
    <li>
      <a href="{% url 'core:book_list' %}">book_list</a>
    </li>
    <li>
      <a href="{% url 'core:book_create' %}">book_create</a>
    </li>
    <li>
      <a href="{% url 'core:book_create2' %}">book_create2</a>
    </li>
    <li>
      <a href="{% url 'core:book_redirected' %}">book_redirected</a>
    </li>
  </ul>
</body>
</html>

myproject/core/templates/my_template.html
<p>{{ name }}</p>